import type { CatalogEntry } from './types.ts';

export const commonEntries: CatalogEntry[] = [
  {
    id: 'EG-C01',
    quality: 'responsiveness',
    domain: 'common',
    feel: 'feels instant, reacts the moment I touch it',
    objective: 'Every user input is answered before the user perceives a wait.',
    keyResults: [
      { id: 'KR-C01a', target: { metric: 'api_latency', threshold: 100, unit: 'ms', percentile: 95 }, note: 'per interactive request' },
      { id: 'KR-C01b', target: { metric: 'time_to_feedback', threshold: 100, unit: 'ms' }, note: 'input to first visible reaction' },
      { id: 'KR-C01c', target: { metric: 'task_completion', threshold: 1000, unit: 'ms' }, note: 'single user-perceived task' },
    ],
    patterns: [
      {
        id: 'TP-C01-1',
        kind: 'performance',
        title: 'Latency guardrail',
        draft: 'Given the target endpoint under a fixed load profile, when N requests are measured externally, then p95 latency must be within the budget.',
        verifiesKeyResults: ['KR-C01a'],
      },
      {
        id: 'TP-C01-2',
        kind: 'e2e',
        title: 'Input-to-reaction',
        draft: 'Given the page is idle, when the user types into the target input, then the first visible DOM change must occur within the budget.',
        verifiesKeyResults: ['KR-C01b'],
      },
      {
        id: 'TP-C01-3',
        kind: 'regression',
        title: 'Hot-path regression pin',
        draft: 'Given a recorded baseline p95 for the hot path, when the current build is measured, then latency must not regress beyond the agreed tolerance.',
        verifiesKeyResults: ['KR-C01a'],
      },
    ],
    typicalExemptions: ['authentication (login, registration)', 'checkout/payment', 'report generation', 'batch exports'],
  },
  {
    id: 'EG-C02',
    quality: 'smoothness',
    domain: 'common',
    feel: 'scrolling is buttery, animations do not stutter',
    objective: 'Motion on screen never visibly hitches.',
    keyResults: [
      { id: 'KR-C02a', target: { metric: 'frame_time', threshold: 16.7, unit: 'ms' }, note: 'sustained during interaction (60fps)' },
      { id: 'KR-C02b', target: { metric: 'long_task_count', threshold: 0, unit: 'count' }, note: 'main-thread tasks over 50ms during interaction' },
      { id: 'KR-C02c', target: { metric: 'dropped_frame_ratio', threshold: 1, unit: '%' }, note: 'during scripted scroll or animation' },
    ],
    patterns: [
      {
        id: 'TP-C02-1',
        kind: 'performance',
        title: 'Scroll trace guardrail',
        draft: 'Given a scripted scroll over representative content, when a frame trace is recorded externally, then the dropped-frame ratio must stay within the budget.',
        verifiesKeyResults: ['KR-C02c'],
      },
      {
        id: 'TP-C02-2',
        kind: 'integration',
        title: 'Long-task audit',
        draft: 'Given the key interaction is triggered, when main-thread tasks are traced, then no task may exceed 50ms.',
        verifiesKeyResults: ['KR-C02b'],
      },
    ],
    typicalExemptions: ['initial data import screens', 'developer/admin tooling views'],
  },
  {
    id: 'EG-C03',
    quality: 'feedback',
    domain: 'common',
    feel: 'I know it heard me, the button reacts when pressed',
    objective: 'Every user action is visibly acknowledged, even when the result takes longer.',
    keyResults: [
      { id: 'KR-C03a', target: { metric: 'time_to_feedback', threshold: 100, unit: 'ms' }, note: 'visible pending or acknowledgement state' },
      { id: 'KR-C03b', target: { metric: 'unacknowledged_action_count', threshold: 0, unit: 'count' }, note: 'every async mutation path has an in-flight UI state' },
    ],
    patterns: [
      {
        id: 'TP-C03-1',
        kind: 'e2e',
        title: 'Acknowledgement timing',
        draft: 'Given a mutating action (submit, delete), when the user triggers it, then a pending indicator must appear within the budget even under throttled network.',
        verifiesKeyResults: ['KR-C03a'],
      },
      {
        id: 'TP-C03-2',
        kind: 'contract',
        title: 'In-flight state contract',
        draft: 'Given the UI state machine, when any mutation is dispatched, then a corresponding in-flight state must exist and be rendered.',
        verifiesKeyResults: ['KR-C03b'],
      },
    ],
    typicalExemptions: ['background sync', 'prefetching', 'telemetry'],
  },
  {
    id: 'EG-C04',
    quality: 'stability_feel',
    domain: 'common',
    feel: 'never crashes, nothing jumps around, it does not lose my input',
    objective: 'The product never betrays the user’s trust mid-task.',
    keyResults: [
      { id: 'KR-C04a', target: { metric: 'crash_count', threshold: 0, unit: 'count' }, note: 'across the critical flows' },
      { id: 'KR-C04b', target: { metric: 'unhandled_error_rate', threshold: 0.1, unit: '%' }, note: 'of sessions' },
      { id: 'KR-C04c', target: { metric: 'layout_shift', threshold: 0.1, unit: 'score' }, note: 'CLS on interactive pages' },
    ],
    patterns: [
      {
        id: 'TP-C04-1',
        kind: 'flaky',
        title: 'Critical-flow soak',
        draft: 'Given the critical flow, when it is repeated N times consecutively by the external runner, then zero runs may fail or crash.',
        verifiesKeyResults: ['KR-C04a'],
      },
      {
        id: 'TP-C04-2',
        kind: 'integration',
        title: 'Error-boundary coverage',
        draft: 'Given a component throws, when rendering continues, then the failure is contained and user input elsewhere is preserved.',
        verifiesKeyResults: ['KR-C04b'],
      },
      {
        id: 'TP-C04-3',
        kind: 'e2e',
        title: 'Layout-shift guardrail',
        draft: 'Given the page loads with realistic data, when CLS is measured externally, then it must stay within the budget.',
        verifiesKeyResults: ['KR-C04c'],
      },
    ],
    typicalExemptions: ['experimental feature-flagged surfaces explicitly marked beta'],
  },
  {
    id: 'EG-C05',
    quality: 'consistency',
    domain: 'common',
    feel: 'always takes about the same time, predictable',
    objective: 'The same action feels the same every time.',
    keyResults: [
      { id: 'KR-C05a', target: { metric: 'latency_spread_p99_over_p50', threshold: 3, unit: 'ratio' }, note: 'for the same interaction' },
      { id: 'KR-C05b', target: { metric: 'cross_run_variance', threshold: 1, unit: 'band' }, note: 'repeated identical requests stay within the agreed variance band' },
    ],
    patterns: [
      {
        id: 'TP-C05-1',
        kind: 'performance',
        title: 'Spread guardrail',
        draft: 'Given a latency distribution collected externally over N requests, when percentiles are computed, then p99 must stay within the multiplier budget of p50.',
        verifiesKeyResults: ['KR-C05a'],
      },
      {
        id: 'TP-C05-2',
        kind: 'integration',
        title: 'Repeat-identity check',
        draft: 'Given the same request issued repeatedly, when responses are compared, then results and timing class must be stable.',
        verifiesKeyResults: ['KR-C05b'],
      },
    ],
    typicalExemptions: ['first-call-after-deploy warmup', 'cold caches explicitly communicated to the user'],
  },
  {
    id: 'EG-C06',
    quality: 'startup_readiness',
    domain: 'common',
    feel: 'opens ready to use, no long splash screen',
    objective: 'The product is usable the moment the user arrives.',
    keyResults: [
      { id: 'KR-C06a', target: { metric: 'time_to_interactive', threshold: 2000, unit: 'ms' }, note: 'cold start' },
      { id: 'KR-C06b', target: { metric: 'first_meaningful_content', threshold: 1000, unit: 'ms' }, note: 'cold start' },
      { id: 'KR-C06c', target: { metric: 'bundle_size', threshold: 300, unit: 'KB' }, note: 'default proxy budget guarding time-to-interactive; adjust per project' },
    ],
    patterns: [
      {
        id: 'TP-C06-1',
        kind: 'performance',
        title: 'Cold-start measurement',
        draft: 'Given a cleared cache environment, when the app is launched by the external runner, then time-to-interactive must be within the budget.',
        verifiesKeyResults: ['KR-C06a'],
      },
      {
        id: 'TP-C06-2',
        kind: 'contract',
        title: 'Bundle budget',
        draft: 'Given a production build, when asset sizes are computed, then each entry bundle must stay within its size budget.',
        verifiesKeyResults: ['KR-C06c'],
      },
    ],
    typicalExemptions: ['first-run setup wizards', 'initial sync after install', 'first boot with shader pre-compilation or initial asset download, when progress is displayed'],
  },
  {
    id: 'EG-C07',
    quality: 'progress_transparency',
    domain: 'common',
    feel: 'I can see it is working, no dead silence',
    objective: 'When the product must be slow, the user is never left guessing.',
    keyResults: [
      { id: 'KR-C07a', target: { metric: 'time_to_progress_indicator', threshold: 500, unit: 'ms' }, note: 'for any operation expected to exceed 1000ms' },
      { id: 'KR-C07b', target: { metric: 'indeterminate_long_operation_count', threshold: 0, unit: 'count' }, note: 'operations over 10s show determinate progress or an estimate' },
      { id: 'KR-C07c', target: { metric: 'silent_timeout_count', threshold: 0, unit: 'count' }, note: 'every timeout path surfaces a message with a next step' },
    ],
    patterns: [
      {
        id: 'TP-C07-1',
        kind: 'e2e',
        title: 'Slow-path indicator',
        draft: 'Given network throttled to simulate the slow case, when the long operation starts, then a progress indicator must appear within 500ms.',
        verifiesKeyResults: ['KR-C07a'],
      },
      {
        id: 'TP-C07-2',
        kind: 'integration',
        title: 'Timeout messaging',
        draft: 'Given the upstream dependency times out, when the failure surfaces, then the user sees an explanation and a retry affordance, never a silent hang.',
        verifiesKeyResults: ['KR-C07c'],
      },
    ],
    typicalExemptions: ['sub-second operations (handled by responsiveness)'],
  },
  {
    id: 'EG-C08',
    quality: 'recoverability',
    domain: 'common',
    feel: 'mistakes are cheap, I can undo, an error does not wipe my work',
    objective: 'No single mistake or transient failure costs the user their work.',
    keyResults: [
      { id: 'KR-C08a', target: { metric: 'unguarded_destructive_actions', threshold: 0, unit: 'count' }, note: 'destructive actions are undoable or explicitly confirmed' },
      { id: 'KR-C08b', target: { metric: 'input_loss_on_error', threshold: 0, unit: 'count' }, note: 'form state survives a failed submit' },
      { id: 'KR-C08c', target: { metric: 'reentry_after_retry', threshold: 0, unit: 'count' }, note: 'a retry after one transient failure succeeds without re-entry' },
    ],
    patterns: [
      {
        id: 'TP-C08-1',
        kind: 'e2e',
        title: 'Failed-submit preservation',
        draft: 'Given a filled form, when the first submit fails with a server error, then all entered values remain and a second submit succeeds.',
        verifiesKeyResults: ['KR-C08b'],
      },
      {
        id: 'TP-C08-2',
        kind: 'contract',
        title: 'Undo contract',
        draft: 'Given each destructive action in the API surface, when enumerated, then each must map to an undo operation or a confirmation step.',
        verifiesKeyResults: ['KR-C08a'],
      },
    ],
    typicalExemptions: ['explicitly irreversible domain actions where confirmation, not undo, is the guarantee'],
  },
  {
    id: 'EG-C09',
    quality: 'continuity',
    domain: 'common',
    feel: 'picks up where I left off, reload does not reset me',
    objective: 'Interruption never resets the user’s context.',
    keyResults: [
      { id: 'KR-C09a', target: { metric: 'state_loss_on_reload', threshold: 0, unit: 'count' }, note: 'for in-progress work' },
      { id: 'KR-C09b', target: { metric: 'offline_edit_loss', threshold: 0, unit: 'count' }, note: 'offline edits are queued and applied on reconnect' },
      { id: 'KR-C09c', target: { metric: 'work_loss_on_session_expiry', threshold: 0, unit: 'count' }, note: 'work survives re-authentication' },
    ],
    patterns: [
      {
        id: 'TP-C09-1',
        kind: 'e2e',
        title: 'Reload persistence',
        draft: 'Given in-progress work, when the page or app reloads, then the user returns to the same state within one interaction.',
        verifiesKeyResults: ['KR-C09a'],
      },
      {
        id: 'TP-C09-2',
        kind: 'integration',
        title: 'Offline queue',
        draft: 'Given the network drops mid-edit, when connectivity returns, then queued changes apply exactly once.',
        verifiesKeyResults: ['KR-C09b'],
      },
    ],
    typicalExemptions: ['intentionally ephemeral surfaces (incognito-style modes, one-time previews)'],
  },
  {
    id: 'EG-C10',
    quality: 'effortlessness',
    domain: 'common',
    feel: 'it takes two taps, no needless questions',
    objective: 'Core tasks cost the minimum number of decisions and actions.',
    keyResults: [
      { id: 'KR-C10a', target: { metric: 'steps_to_complete', threshold: 5, unit: 'count' }, note: 'default action budget per core task; adjust per project' },
      { id: 'KR-C10b', target: { metric: 'redundant_input_count', threshold: 0, unit: 'count' }, note: 'known data is never asked for twice' },
      { id: 'KR-C10c', target: { metric: 'required_field_count', threshold: 5, unit: 'count' }, note: 'per form; optional fields deferred or defaulted' },
    ],
    patterns: [
      {
        id: 'TP-C10-1',
        kind: 'e2e',
        title: 'Step-count contract',
        draft: 'Given the core task scripted end to end, when discrete user actions are counted, then the total must not exceed the budget.',
        verifiesKeyResults: ['KR-C10a'],
      },
      {
        id: 'TP-C10-2',
        kind: 'integration',
        title: 'Re-entry audit',
        draft: 'Given a returning user who completed the flow before, when they start it again, then previously provided data must be pre-filled.',
        verifiesKeyResults: ['KR-C10b'],
      },
    ],
    typicalExemptions: ['legally mandated confirmations (payment, account deletion)', 'security checkpoints'],
  },
  {
    id: 'EG-C11',
    quality: 'accessibility',
    domain: 'common',
    feel: 'works with just a keyboard, readable, the screen reader says something sensible',
    objective: 'The product is usable without a mouse, perfect vision, or ideal conditions.',
    keyResults: [
      { id: 'KR-C11a', target: { metric: 'keyboard_unreachable_count', threshold: 0, unit: 'count' }, note: 'every interactive element reachable and operable by keyboard' },
      { id: 'KR-C11b', target: { metric: 'contrast_violations', threshold: 0, unit: 'count' }, note: 'WCAG AA on key screens' },
      { id: 'KR-C11c', target: { metric: 'unlabeled_control_count', threshold: 0, unit: 'count' }, note: 'every control exposes an accessible name' },
    ],
    patterns: [
      {
        id: 'TP-C11-1',
        kind: 'e2e',
        title: 'Keyboard-only traversal',
        draft: 'Given the core task, when it is driven using only the keyboard, then it must complete, with visible focus at every step.',
        verifiesKeyResults: ['KR-C11a'],
      },
      {
        id: 'TP-C11-2',
        kind: 'integration',
        title: 'Static accessibility audit',
        draft: 'Given key screens rendered with realistic data, when an accessibility scanner runs, then zero AA violations may remain.',
        verifiesKeyResults: ['KR-C11b'],
      },
      {
        id: 'TP-C11-3',
        kind: 'contract',
        title: 'Label contract',
        draft: 'Given all interactive controls enumerated, when accessible names are checked, then none may be missing.',
        verifiesKeyResults: ['KR-C11c'],
      },
    ],
    typicalExemptions: ['purely decorative visuals', 'canvas-rendered game scenes with platform accessibility options as the equivalent guarantee'],
  },
  {
    id: 'EG-C12',
    quality: 'resource_frugality',
    domain: 'common',
    feel: 'does not heat my phone, does not eat memory',
    objective: 'The product respects the user’s device.',
    keyResults: [
      { id: 'KR-C12a', target: { metric: 'memory_growth_over_session', threshold: 0, unit: 'MB' }, note: 'steady state within budget, no unbounded growth' },
      { id: 'KR-C12b', target: { metric: 'idle_cpu', threshold: 1, unit: '%' }, note: 'while the user is not interacting' },
      { id: 'KR-C12c', target: { metric: 'energy_impact', threshold: 1, unit: 'platform_budget' }, note: 'within the platform budget for a standard session' },
    ],
    patterns: [
      {
        id: 'TP-C12-1',
        kind: 'flaky',
        title: 'Leak soak',
        draft: 'Given a repeating usage scenario driven N times, when memory is sampled after each cycle, then it must return to the baseline band every time.',
        verifiesKeyResults: ['KR-C12a'],
      },
      {
        id: 'TP-C12-2',
        kind: 'performance',
        title: 'Idle drain guardrail',
        draft: 'Given the app left idle for T minutes, when CPU usage and wakeups are measured externally, then both must stay within budget.',
        verifiesKeyResults: ['KR-C12b'],
      },
    ],
    typicalExemptions: ['opt-in heavy modes (export, rendering, benchmarking)'],
  },
];
