import type { CatalogEntry } from './types.ts';

export const gameEntries: CatalogEntry[] = [
  {
    id: 'EG-G01',
    quality: 'control_latency',
    domain: 'game',
    feel: 'the character moves the instant I press, controls feel tight',
    objective: 'Input becomes visible action within frames, not within perceptible delay.',
    keyResults: [
      { id: 'KR-G01a', target: { metric: 'input_to_display', threshold: 50, unit: 'ms' }, note: 'about 3 frames at 60fps, core actions in local play' },
      { id: 'KR-G01b', target: { metric: 'input_drop_count', threshold: 0, unit: 'count' }, note: 'inputs within the buffer window are never lost' },
    ],
    patterns: [
      {
        id: 'TP-G01-1',
        kind: 'performance',
        title: 'Input-to-photon measurement',
        draft: 'Given an instrumented build with input and present timestamps, when a scripted core action fires, then the measured input-to-display latency must be within the budget.',
        verifiesKeyResults: ['KR-G01a'],
      },
      {
        id: 'TP-G01-2',
        kind: 'integration',
        title: 'Input buffer integrity',
        draft: 'Given a scripted input sequence at frame boundaries and under induced frame spikes, when the sequence completes, then every buffered input must have registered exactly once.',
        verifiesKeyResults: ['KR-G01b'],
      },
    ],
    typicalExemptions: ['menus and inventory screens', 'cutscenes', 'turn-based phases'],
  },
  {
    id: 'EG-G02',
    quality: 'frame_pacing',
    domain: 'game',
    feel: 'no hitches mid-fight, no stutter when a new area loads',
    objective: 'Frame delivery stays even under gameplay load; the worst frames stay invisible.',
    keyResults: [
      { id: 'KR-G02a', target: { metric: 'frame_time', threshold: 16.7, unit: 'ms', percentile: 99 }, note: 'frame budget during representative gameplay (33.3ms at 30fps)' },
      { id: 'KR-G02b', target: { metric: 'hitch_count', threshold: 0, unit: 'count' }, note: 'frames over 100ms, including asset streaming and shader compilation' },
    ],
    patterns: [
      {
        id: 'TP-G02-1',
        kind: 'performance',
        title: 'Gameplay trace guardrail',
        draft: 'Given a recorded gameplay segment replayed on an instrumented build, when the frame trace is analyzed, then p99 frame time and hitch count must stay within budget.',
        verifiesKeyResults: ['KR-G02a', 'KR-G02b'],
      },
      {
        id: 'TP-G02-2',
        kind: 'integration',
        title: 'Streaming hitch audit',
        draft: 'Given a scripted traversal crossing asset-streaming boundaries, when frames are traced, then no hitch may exceed the budget.',
        verifiesKeyResults: ['KR-G02b'],
      },
    ],
    typicalExemptions: ['loading screens with progress display'],
  },
  {
    id: 'EG-G03',
    quality: 'netplay_responsiveness',
    domain: 'game',
    feel: 'online feels like offline, my shots register',
    objective: 'Networked actions feel locally executed within the supported connection envelope.',
    keyResults: [
      { id: 'KR-G03a', target: { metric: 'perceived_action_latency', threshold: 100, unit: 'ms' }, note: 'at the supported RTT ceiling, via prediction and lag compensation' },
      { id: 'KR-G03b', target: { metric: 'tick_overrun_count', threshold: 0, unit: 'count' }, note: 'actions processed within one server tick; tick duration p99 fits the tick interval at target load' },
    ],
    patterns: [
      {
        id: 'TP-G03-1',
        kind: 'e2e',
        title: 'Emulated-RTT action test',
        draft: 'Given two headless clients connected through network emulation at the supported RTT ceiling, when a scripted action fires, then the acting client’s perceived action latency must be within the budget.',
        verifiesKeyResults: ['KR-G03a'],
      },
      {
        id: 'TP-G03-2',
        kind: 'performance',
        title: 'Tick budget guardrail',
        draft: 'Given the server under representative match load, when tick durations are measured externally, then p99 tick duration must fit the tick interval.',
        verifiesKeyResults: ['KR-G03b'],
      },
    ],
    typicalExemptions: ['lobby', 'chat', 'inventory', 'shop'],
  },
  {
    id: 'EG-G04',
    quality: 'sync_integrity',
    domain: 'game',
    feel: 'we all see the same game, no rubber-banding, no phantom hits',
    objective: 'All peers agree on the game state, and corrections stay imperceptible.',
    keyResults: [
      { id: 'KR-G04a', target: { metric: 'desync_count', threshold: 0, unit: 'count' }, note: 'across a full match, verified by periodic state checksums' },
      { id: 'KR-G04b', target: { metric: 'rollback_depth', threshold: 3, unit: 'frames' }, note: 'at the supported RTT ceiling — corrections stay invisible' },
      { id: 'KR-G04c', target: { metric: 'authority_divergence', threshold: 1, unit: 'units' }, note: 'client prediction vs server authority outside correction windows; adjust per game' },
    ],
    patterns: [
      {
        id: 'TP-G04-1',
        kind: 'regression',
        title: 'Deterministic replay check',
        draft: 'Given the same input script run on two simulation instances, when state checksums are compared every N frames, then all checksums must match.',
        verifiesKeyResults: ['KR-G04a'],
      },
      {
        id: 'TP-G04-2',
        kind: 'integration',
        title: 'Rollback depth audit',
        draft: 'Given emulated jitter at the supported RTT ceiling, when a scripted exchange runs, then no correction may exceed the budgeted rollback depth.',
        verifiesKeyResults: ['KR-G04b'],
      },
      {
        id: 'TP-G04-3',
        kind: 'integration',
        title: 'Authority divergence guardrail',
        draft: 'Given a scripted movement pattern under emulated latency, when client and server positions are sampled, then divergence must stay within the threshold.',
        verifiesKeyResults: ['KR-G04c'],
      },
    ],
    typicalExemptions: ['spectator/replay views with declared delay'],
  },
  {
    id: 'EG-G05',
    quality: 'disruption_tolerance',
    domain: 'game',
    feel: 'a bad connection bends the game, it does not break it',
    objective: 'Real-world network conditions degrade the experience gracefully, never catastrophically.',
    keyResults: [
      { id: 'KR-G05a', target: { metric: 'degradation_failures', threshold: 0, unit: 'count' }, note: 'playable at packet loss ≤ 5% and jitter ≤ 30ms: inputs accepted, state advances, no crash or desync' },
      { id: 'KR-G05b', target: { metric: 'reconnect_to_match', threshold: 10000, unit: 'ms' }, note: 'after a transient disconnect, with match state restored' },
      { id: 'KR-G05c', target: { metric: 'grace_window_losses', threshold: 0, unit: 'count' }, note: 'no forfeit or progress loss within the declared grace window' },
    ],
    patterns: [
      {
        id: 'TP-G05-1',
        kind: 'flaky',
        title: 'Degraded-network soak',
        draft: 'Given a scripted match under emulated loss and jitter at the budget boundary, when the match runs to completion N times, then zero runs may crash, desync, or become unplayable.',
        verifiesKeyResults: ['KR-G05a'],
      },
      {
        id: 'TP-G05-2',
        kind: 'e2e',
        title: 'Rejoin flow',
        draft: 'Given a client whose connection is killed mid-match, when it reconnects within the grace window, then it rejoins the same match with state restored within the budget.',
        verifiesKeyResults: ['KR-G05b', 'KR-G05c'],
      },
    ],
    typicalExemptions: ['sustained outages beyond the declared grace window', 'tournament modes with stricter declared rules'],
  },
  {
    id: 'EG-G06',
    quality: 'matchmaking_flow',
    domain: 'game',
    feel: 'I get into a match fast, opponents feel about my level',
    objective: 'Getting into a fair match is fast and predictable.',
    keyResults: [
      { id: 'KR-G06a', target: { metric: 'queue_time', threshold: 120000, unit: 'ms', percentile: 90 }, note: 'regional budget at the reference player population' },
      { id: 'KR-G06b', target: { metric: 'skill_delta', threshold: 1, unit: 'tier' }, note: 'between matched players for ranked modes' },
      { id: 'KR-G06c', target: { metric: 'match_abort_rate', threshold: 1, unit: '%' }, note: 'formed matches start instead of dissolving' },
    ],
    patterns: [
      {
        id: 'TP-G06-1',
        kind: 'integration',
        title: 'Simulated-pool matchmaking',
        draft: 'Given a synthetic player population with a realistic skill distribution, when matchmaking runs, then p90 queue time and per-match skill delta must stay within budget.',
        verifiesKeyResults: ['KR-G06a', 'KR-G06b'],
      },
      {
        id: 'TP-G06-2',
        kind: 'flaky',
        title: 'Match formation soak',
        draft: 'Given N matchmaking cycles driven by headless clients, when results are tallied, then the abort rate must stay within budget.',
        verifiesKeyResults: ['KR-G06c'],
      },
    ],
    typicalExemptions: ['off-peak population', 'placement matches'],
  },
  {
    id: 'EG-G07',
    quality: 'load_seamlessness',
    domain: 'game',
    feel: 'the world just continues, fast travel is fast',
    objective: 'In-game transitions never eject the player from the experience.',
    keyResults: [
      { id: 'KR-G07a', target: { metric: 'scene_load', threshold: 5000, unit: 'ms', percentile: 95 }, note: 'area transitions and fast travel' },
      { id: 'KR-G07b', target: { metric: 'input_lockout', threshold: 200, unit: 'ms' }, note: 'during masked transitions — the game acknowledges input while loading' },
      { id: 'KR-G07c', target: { metric: 'visible_pop_in_count', threshold: 0, unit: 'count' }, note: 'within the declared tolerance during in-world streaming' },
    ],
    patterns: [
      {
        id: 'TP-G07-1',
        kind: 'performance',
        title: 'Transition timing sweep',
        draft: 'Given every major transition scripted (area changes, fast travel, respawn), when load times are measured externally, then p95 must stay within budget.',
        verifiesKeyResults: ['KR-G07a'],
      },
      {
        id: 'TP-G07-2',
        kind: 'e2e',
        title: 'Masked-transition input check',
        draft: 'Given inputs sent during a masked transition, when the transition completes, then each input must have been acknowledged within the lockout budget.',
        verifiesKeyResults: ['KR-G07b'],
      },
    ],
    typicalExemptions: ['initial boot (startup_readiness)', 'platform-mandated screens'],
  },
  {
    id: 'EG-G08',
    quality: 'audio_visual_sync',
    domain: 'game',
    feel: 'hits sound when they land, no lip-sync drift',
    objective: 'What the player hears matches what they see, frame-close.',
    keyResults: [
      { id: 'KR-G08a', target: { metric: 'av_offset', threshold: 45, unit: 'ms' }, note: 'between a visual event and its sound' },
      { id: 'KR-G08b', target: { metric: 'audio_dropout_count', threshold: 0, unit: 'count' }, note: 'during representative gameplay' },
      { id: 'KR-G08c', target: { metric: 'input_to_audio', threshold: 50, unit: 'ms' }, note: 'rhythm/timing-critical modes: fits the declared judgment window' },
    ],
    patterns: [
      {
        id: 'TP-G08-1',
        kind: 'integration',
        title: 'Event-sync capture',
        draft: 'Given an instrumented build emitting timestamps for impact frames and sound onsets, when N scripted events fire, then every offset must stay within budget.',
        verifiesKeyResults: ['KR-G08a'],
      },
      {
        id: 'TP-G08-2',
        kind: 'flaky',
        title: 'Dropout soak',
        draft: 'Given full-session audio captured during scripted gameplay, when analyzed, then zero dropouts or glitches may appear.',
        verifiesKeyResults: ['KR-G08b'],
      },
    ],
    typicalExemptions: ['designed audio delay (distance attenuation, echo)'],
  },
  {
    id: 'EG-G09',
    quality: 'fairness_feel',
    domain: 'game',
    feel: 'I died because I was outplayed, not because of the network',
    objective: 'Network conditions and implementation details never grant one player an unearned edge.',
    keyResults: [
      { id: 'KR-G09a', target: { metric: 'hit_registration_disagreement', threshold: 5, unit: '%' }, note: 'client-perceived hits confirmed by the server within tolerance, symmetric across players' },
      { id: 'KR-G09b', target: { metric: 'peeker_advantage', threshold: 100, unit: 'ms' }, note: 'at the supported RTT asymmetry' },
      { id: 'KR-G09c', target: { metric: 'client_only_trust_count', threshold: 0, unit: 'count' }, note: 'every gameplay-critical action validated server-side' },
    ],
    patterns: [
      {
        id: 'TP-G09-1',
        kind: 'integration',
        title: 'Asymmetric-RTT duel',
        draft: 'Given two scripted clients under asymmetric emulated latency, when standard duels run in both directions, then hit agreement and peeker advantage must stay within budget for both sides.',
        verifiesKeyResults: ['KR-G09a', 'KR-G09b'],
      },
      {
        id: 'TP-G09-2',
        kind: 'contract',
        title: 'Authority contract',
        draft: 'Given all gameplay-critical actions enumerated, when server handling is checked, then each must have server-side validation.',
        verifiesKeyResults: ['KR-G09c'],
      },
      {
        id: 'TP-G09-3',
        kind: 'security',
        title: 'Out-of-envelope rejection',
        draft: 'Given a modified client submitting impossible movement or actions, when the server processes them, then it must reject them and keep shared state consistent.',
        verifiesKeyResults: ['KR-G09c'],
      },
    ],
    typicalExemptions: ['casual/custom modes with declared rules'],
  },
  {
    id: 'EG-G10',
    quality: 'progression_integrity',
    domain: 'game',
    feel: 'my save is sacred, a crash costs me minutes, not hours',
    objective: 'Player progress survives crashes, power loss, and sync conflicts.',
    keyResults: [
      { id: 'KR-G10a', target: { metric: 'corrupted_save_count', threshold: 0, unit: 'count' }, note: 'interrupting a save never corrupts; the last good save always loads' },
      { id: 'KR-G10b', target: { metric: 'progress_loss_after_crash', threshold: 300000, unit: 'ms' }, note: 'within the declared autosave interval (default 5 minutes)' },
      { id: 'KR-G10c', target: { metric: 'sync_policy_violations', threshold: 0, unit: 'count' }, note: 'cloud conflicts resolve by the declared policy, never silently discarding newer progress' },
    ],
    patterns: [
      {
        id: 'TP-G10-1',
        kind: 'integration',
        title: 'Kill-during-save',
        draft: 'Given the process terminated mid-save repeatedly at randomized offsets, when the game relaunches, then a valid save must load every time.',
        verifiesKeyResults: ['KR-G10a'],
      },
      {
        id: 'TP-G10-2',
        kind: 'e2e',
        title: 'Crash loss bound',
        draft: 'Given scripted play followed by a forced crash, when the game relaunches, then lost progress must fit within the autosave window.',
        verifiesKeyResults: ['KR-G10b'],
      },
      {
        id: 'TP-G10-3',
        kind: 'integration',
        title: 'Conflict matrix',
        draft: 'Given constructed divergent local and cloud saves for each conflict class, when sync runs, then resolution must follow the declared policy in every case.',
        verifiesKeyResults: ['KR-G10c'],
      },
    ],
    typicalExemptions: ['hardcore/permadeath modes'],
  },
];
